version: '3'
services:
  wp:
    image: wordpress:latest 
    container_name: wp
    ports:
      - 80:80 
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project 
      #- wp-app:/var/www/html 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DATABASE_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db
    links:
      - db 
  
  pma:
  # https://docs.phpmyadmin.net/en/latest/setup.html
    image: phpmyadmin:latest
    container_name: pma
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 8090:80
    links:
      - db
    depends_on:
      - db 

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
      - 33060:33060
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"  
      
volumes:
  db_data:
  wp_app:
